// Re-export icons with stable app-friendly names.
// If we switch from hugeicons to another library, only this file changes.

export {
  AddCircleHalfDotIcon as IssuesIcon,
  AlertCircleIcon,
  ArrangeIcon as SortIcon,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowLeft01Icon as ChevronLeftIcon,
  ArrowReloadHorizontalIcon as RefreshCwIcon,
  ArrowRight01Icon as ChevronRightIcon,
  ArrowUp01Icon as ChevronUpIcon,
  BookOpen01Icon as BookOpenIcon,
  Bug01Icon as BugIcon,
  Calendar01Icon as CalendarIcon,
  Cancel01Icon as CloseIcon,
  Cancel01Icon as XIcon,
  CheckListIcon as ReviewsIcon,
  CircleIcon,
  Clock01Icon as ClockIcon,
  CodeIcon,
  Comment01Icon as CommentIcon,
  ComputerIcon as SystemIcon,
  Copy01Icon as CopyIcon,
  DashboardSquare01Icon as DashboardIcon,
  Delete01Icon,
  DragDropVerticalIcon as GripVerticalIcon,
  File02Icon as FileIcon,
  Folder01Icon as FolderIcon,
  FolderLibraryIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitMergeIcon,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  GitPullRequestIcon,
  Home01Icon as HomeIcon,
  InboxIcon,
  Loading03Icon as LoaderCircleIcon,
  Message01Icon as MessageIcon,
  Moon01Icon as MoonIcon,
  MoreHorizontalIcon,
  Notification01Icon as NotificationIcon,
  PencilEdit01Icon as EditIcon,
  PlusSignIcon,
  Remove01Icon,
  Search01Icon as SearchIcon,
  Settings01Icon as SettingsIcon,
  SidebarLeftIcon as PanelLeftIcon,
  StarIcon,
  Sun01Icon as SunIcon,
  Tick02Icon as CheckIcon,
  Tick02Icon as TickIcon,
  UserAdd01Icon as UserAddIcon,
  UserCircleIcon,
  ViewIcon,
} from "@hugeicons/react";
export { GitHubLogo, GitHubWordmarkLogo } from "./brand-logos";
