// Re-export icons with stable app-friendly names.
// If we switch from hugeicons to another library, only this file changes.

export {
  AddCircleHalfDotIcon as IssuesIcon,
  AlertCircleIcon,
  ArchiveIcon,
  ArrangeIcon as SortIcon,
  ArrowDown01Icon as ChevronDownIcon,
  ArrowLeft01Icon as ChevronLeftIcon,
  ArrowReloadHorizontalIcon as RefreshCwIcon,
  ArrowRight01Icon as ChevronRightIcon,
  ArrowUp01Icon as ChevronUpIcon,
  BookOpen01Icon as BookOpenIcon,
  Bug01Icon as BugIcon,
  Building03Icon as BuildingIcon,
  Calendar01Icon as CalendarIcon,
  Cancel01Icon as CloseIcon,
  Cancel01Icon as XIcon,
  CheckListIcon as ReviewsIcon,
  CircleIcon,
  Clock01Icon as ClockIcon,
  CommandIcon,
  Comment01Icon as CommentIcon,
  ComputerIcon as SystemIcon,
  Copy01Icon as CopyIcon,
  DashboardSquare01Icon as DashboardIcon,
  Delete01Icon,
  Download02Icon as DownloadIcon,
  DragDropVerticalIcon as GripVerticalIcon,
  File02Icon as FileIcon,
  Folder01Icon as FolderIcon,
  FolderLibraryIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitForkIcon,
  GitMergeIcon,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  GitPullRequestIcon,
  Home01Icon as HomeIcon,
  InboxIcon,
  Link01Icon as LinkIcon,
  Link02Icon as ExternalLinkIcon,
  Loading03Icon as LoaderCircleIcon,
  Location01Icon as LocationIcon,
  LockIcon,
  Mail01Icon as MailIcon,
  Message01Icon as MessageIcon,
  Moon02Icon as MoonIcon,
  MoreHorizontalIcon,
  Notification01Icon as NotificationIcon,
  PencilEdit01Icon as EditIcon,
  PlusSignIcon,
  Remove01Icon,
  Search01Icon as SearchIcon,
  Settings01Icon as SettingsIcon,
  SidebarLeftIcon as PanelLeftIcon,
  SourceCodeIcon as CodeIcon,
  StarIcon,
  Sun01Icon as SunIcon,
  Tick02Icon as CheckIcon,
  Tick02Icon as TickIcon,
  UserAdd01Icon as UserAddIcon,
  UserCircleIcon,
  UserGroupIcon as FollowersIcon,
  ViewIcon,
  WifiDisconnected01Icon as WifiOffIcon,
} from "@hugeicons/react";
export { GitHubLogo, GitHubWordmarkLogo } from "./brand-logos";
export { PenIcon } from "./pen-icon";
export { SeparatorHorizontalIcon } from "./separator-horizontal-icon";
