// Re-export icons with stable app-friendly names.
// If we switch from hugeicons to another library, only this file changes.

export {
  AddCircleHalfDotIcon as IssuesIcon,
  BookOpen01Icon as BookOpenIcon,
  Bug01Icon as BugIcon,
  Calendar01Icon as CalendarIcon,
  Cancel01Icon as CloseIcon,
  CheckListIcon as ReviewsIcon,
  Clock01Icon as ClockIcon,
  CodeIcon,
  Comment01Icon as CommentIcon,
  ComputerIcon as SystemIcon,
  Copy01Icon as CopyIcon,
  DashboardSquare01Icon as DashboardIcon,
  File02Icon as FileIcon,
  Folder01Icon as FolderIcon,
  FolderLibraryIcon,
  GitBranchIcon,
  GitCommitIcon,
  GitMergeIcon,
  GitPullRequestClosedIcon,
  GitPullRequestDraftIcon,
  GitPullRequestIcon,
  Home01Icon as HomeIcon,
  InboxIcon,
  Message01Icon as MessageIcon,
  Moon01Icon as MoonIcon,
  MoreHorizontalIcon,
  Notification01Icon as NotificationIcon,
  Search01Icon as SearchIcon,
  Settings01Icon as SettingsIcon,
  StarIcon,
  Sun01Icon as SunIcon,
  Tick02Icon as TickIcon,
  ViewIcon,
} from "@hugeicons/react";
export { GitHubLogo, GitHubWordmarkLogo } from "./brand-logos";
