// Env types are generated by `wrangler types` in worker-configuration.d.ts
// The cloudflare:workers module exports env: Cloudflare.Env from worker-configuration.d.ts

declare namespace Cloudflare {
	interface Env {
		/** Public base URL for R2 comment media (custom domain or r2.dev). */
		R2_PUBLIC_BASE_URL?: string;
		GITHUB_OAUTH_CLIENT_ID?: string;
		GITHUB_OAUTH_CLIENT_SECRET?: string;
		GITHUB_APP_CLIENT_ID?: string;
		GITHUB_APP_CLIENT_SECRET?: string;
		GITHUB_APP_ID?: string;
		GITHUB_APP_PRIVATE_KEY?: string;
		GITHUB_APP_SLUG?: string;
		GITHUB_WEBHOOK_SECRET?: string;
		GITHUB_CLIENT_ID?: string;
		GITHUB_CLIENT_SECRET?: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		SIGNAL_RELAY: DurableObjectNamespace;
	}
}
