/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedReviewsRouteImport } from './routes/_protected/reviews'
import { Route as ProtectedReposRouteImport } from './routes/_protected/repos'
import { Route as ProtectedPullsRouteImport } from './routes/_protected/pulls'
import { Route as ProtectedIssuesRouteImport } from './routes/_protected/issues'
import { Route as ProtectedInboxRouteImport } from './routes/_protected/inbox'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedOwnerIndexRouteImport } from './routes/_protected/$owner/index'
import { Route as ApiWebhooksGithubRouteImport } from './routes/api/webhooks/github'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedSettingsShortcutsRouteImport } from './routes/_protected/settings/shortcuts'
import { Route as ProtectedOwnerRepoIndexRouteImport } from './routes/_protected/$owner/$repo/index'
import { Route as ApiGithubAppCallbackRouteImport } from './routes/api/github/app/callback'
import { Route as ApiGithubAppAuthorizeRouteImport } from './routes/api/github/app/authorize'
import { Route as ProtectedOwnerRepoPullsRouteImport } from './routes/_protected/$owner/$repo/pulls'
import { Route as ProtectedOwnerRepoIssuesIndexRouteImport } from './routes/_protected/$owner/$repo/issues.index'
import { Route as ProtectedOwnerRepoTreeSplatRouteImport } from './routes/_protected/$owner/$repo/tree.$'
import { Route as ProtectedOwnerRepoReviewPullIdRouteImport } from './routes/_protected/$owner/$repo/review.$pullId'
import { Route as ProtectedOwnerRepoPullPullIdRouteImport } from './routes/_protected/$owner/$repo/pull.$pullId'
import { Route as ProtectedOwnerRepoIssuesNewRouteImport } from './routes/_protected/$owner/$repo/issues.new'
import { Route as ProtectedOwnerRepoIssuesIssueIdRouteImport } from './routes/_protected/$owner/$repo/issues.$issueId'
import { Route as ProtectedOwnerRepoCompareSplatRouteImport } from './routes/_protected/$owner/$repo/compare.$'
import { Route as ProtectedOwnerRepoCommitShaRouteImport } from './routes/_protected/$owner/$repo/commit.$sha'
import { Route as ProtectedOwnerRepoBlobSplatRouteImport } from './routes/_protected/$owner/$repo/blob.$'
import { Route as ProtectedOwnerRepoActionsRunsRunIdRouteImport } from './routes/_protected/$owner/$repo/actions.runs.$runId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReviewsRoute = ProtectedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReposRoute = ProtectedReposRouteImport.update({
  id: '/repos',
  path: '/repos',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPullsRoute = ProtectedPullsRouteImport.update({
  id: '/pulls',
  path: '/pulls',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIssuesRoute = ProtectedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedInboxRoute = ProtectedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsRoute,
} as any)
const ProtectedOwnerIndexRoute = ProtectedOwnerIndexRouteImport.update({
  id: '/$owner/',
  path: '/$owner/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiWebhooksGithubRoute = ApiWebhooksGithubRouteImport.update({
  id: '/api/webhooks/github',
  path: '/api/webhooks/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingsShortcutsRoute =
  ProtectedSettingsShortcutsRouteImport.update({
    id: '/shortcuts',
    path: '/shortcuts',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedOwnerRepoIndexRoute = ProtectedOwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiGithubAppCallbackRoute = ApiGithubAppCallbackRouteImport.update({
  id: '/api/github/app/callback',
  path: '/api/github/app/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubAppAuthorizeRoute = ApiGithubAppAuthorizeRouteImport.update({
  id: '/api/github/app/authorize',
  path: '/api/github/app/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedOwnerRepoPullsRoute = ProtectedOwnerRepoPullsRouteImport.update({
  id: '/$owner/$repo/pulls',
  path: '/$owner/$repo/pulls',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOwnerRepoIssuesIndexRoute =
  ProtectedOwnerRepoIssuesIndexRouteImport.update({
    id: '/$owner/$repo/issues/',
    path: '/$owner/$repo/issues/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoTreeSplatRoute =
  ProtectedOwnerRepoTreeSplatRouteImport.update({
    id: '/$owner/$repo/tree/$',
    path: '/$owner/$repo/tree/$',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoReviewPullIdRoute =
  ProtectedOwnerRepoReviewPullIdRouteImport.update({
    id: '/$owner/$repo/review/$pullId',
    path: '/$owner/$repo/review/$pullId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoPullPullIdRoute =
  ProtectedOwnerRepoPullPullIdRouteImport.update({
    id: '/$owner/$repo/pull/$pullId',
    path: '/$owner/$repo/pull/$pullId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoIssuesNewRoute =
  ProtectedOwnerRepoIssuesNewRouteImport.update({
    id: '/$owner/$repo/issues/new',
    path: '/$owner/$repo/issues/new',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoIssuesIssueIdRoute =
  ProtectedOwnerRepoIssuesIssueIdRouteImport.update({
    id: '/$owner/$repo/issues/$issueId',
    path: '/$owner/$repo/issues/$issueId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoCompareSplatRoute =
  ProtectedOwnerRepoCompareSplatRouteImport.update({
    id: '/$owner/$repo/compare/$',
    path: '/$owner/$repo/compare/$',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoCommitShaRoute =
  ProtectedOwnerRepoCommitShaRouteImport.update({
    id: '/$owner/$repo/commit/$sha',
    path: '/$owner/$repo/commit/$sha',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoBlobSplatRoute =
  ProtectedOwnerRepoBlobSplatRouteImport.update({
    id: '/$owner/$repo/blob/$',
    path: '/$owner/$repo/blob/$',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOwnerRepoActionsRunsRunIdRoute =
  ProtectedOwnerRepoActionsRunsRunIdRouteImport.update({
    id: '/$owner/$repo/actions/runs/$runId',
    path: '/$owner/$repo/actions/runs/$runId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/inbox': typeof ProtectedInboxRoute
  '/issues': typeof ProtectedIssuesRoute
  '/pulls': typeof ProtectedPullsRoute
  '/repos': typeof ProtectedReposRoute
  '/reviews': typeof ProtectedReviewsRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/settings/shortcuts': typeof ProtectedSettingsShortcutsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/$owner/': typeof ProtectedOwnerIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/$owner/$repo/pulls': typeof ProtectedOwnerRepoPullsRoute
  '/api/github/app/authorize': typeof ApiGithubAppAuthorizeRoute
  '/api/github/app/callback': typeof ApiGithubAppCallbackRoute
  '/$owner/$repo/': typeof ProtectedOwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof ProtectedOwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof ProtectedOwnerRepoCommitShaRoute
  '/$owner/$repo/compare/$': typeof ProtectedOwnerRepoCompareSplatRoute
  '/$owner/$repo/issues/$issueId': typeof ProtectedOwnerRepoIssuesIssueIdRoute
  '/$owner/$repo/issues/new': typeof ProtectedOwnerRepoIssuesNewRoute
  '/$owner/$repo/pull/$pullId': typeof ProtectedOwnerRepoPullPullIdRoute
  '/$owner/$repo/review/$pullId': typeof ProtectedOwnerRepoReviewPullIdRoute
  '/$owner/$repo/tree/$': typeof ProtectedOwnerRepoTreeSplatRoute
  '/$owner/$repo/issues/': typeof ProtectedOwnerRepoIssuesIndexRoute
  '/$owner/$repo/actions/runs/$runId': typeof ProtectedOwnerRepoActionsRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/inbox': typeof ProtectedInboxRoute
  '/issues': typeof ProtectedIssuesRoute
  '/pulls': typeof ProtectedPullsRoute
  '/repos': typeof ProtectedReposRoute
  '/reviews': typeof ProtectedReviewsRoute
  '/': typeof ProtectedIndexRoute
  '/settings/shortcuts': typeof ProtectedSettingsShortcutsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/$owner': typeof ProtectedOwnerIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/$owner/$repo/pulls': typeof ProtectedOwnerRepoPullsRoute
  '/api/github/app/authorize': typeof ApiGithubAppAuthorizeRoute
  '/api/github/app/callback': typeof ApiGithubAppCallbackRoute
  '/$owner/$repo': typeof ProtectedOwnerRepoIndexRoute
  '/$owner/$repo/blob/$': typeof ProtectedOwnerRepoBlobSplatRoute
  '/$owner/$repo/commit/$sha': typeof ProtectedOwnerRepoCommitShaRoute
  '/$owner/$repo/compare/$': typeof ProtectedOwnerRepoCompareSplatRoute
  '/$owner/$repo/issues/$issueId': typeof ProtectedOwnerRepoIssuesIssueIdRoute
  '/$owner/$repo/issues/new': typeof ProtectedOwnerRepoIssuesNewRoute
  '/$owner/$repo/pull/$pullId': typeof ProtectedOwnerRepoPullPullIdRoute
  '/$owner/$repo/review/$pullId': typeof ProtectedOwnerRepoReviewPullIdRoute
  '/$owner/$repo/tree/$': typeof ProtectedOwnerRepoTreeSplatRoute
  '/$owner/$repo/issues': typeof ProtectedOwnerRepoIssuesIndexRoute
  '/$owner/$repo/actions/runs/$runId': typeof ProtectedOwnerRepoActionsRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/setup': typeof SetupRoute
  '/terms': typeof TermsRoute
  '/_protected/inbox': typeof ProtectedInboxRoute
  '/_protected/issues': typeof ProtectedIssuesRoute
  '/_protected/pulls': typeof ProtectedPullsRoute
  '/_protected/repos': typeof ProtectedReposRoute
  '/_protected/reviews': typeof ProtectedReviewsRoute
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/settings/shortcuts': typeof ProtectedSettingsShortcutsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhooks/github': typeof ApiWebhooksGithubRoute
  '/_protected/$owner/': typeof ProtectedOwnerIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/$owner/$repo/pulls': typeof ProtectedOwnerRepoPullsRoute
  '/api/github/app/authorize': typeof ApiGithubAppAuthorizeRoute
  '/api/github/app/callback': typeof ApiGithubAppCallbackRoute
  '/_protected/$owner/$repo/': typeof ProtectedOwnerRepoIndexRoute
  '/_protected/$owner/$repo/blob/$': typeof ProtectedOwnerRepoBlobSplatRoute
  '/_protected/$owner/$repo/commit/$sha': typeof ProtectedOwnerRepoCommitShaRoute
  '/_protected/$owner/$repo/compare/$': typeof ProtectedOwnerRepoCompareSplatRoute
  '/_protected/$owner/$repo/issues/$issueId': typeof ProtectedOwnerRepoIssuesIssueIdRoute
  '/_protected/$owner/$repo/issues/new': typeof ProtectedOwnerRepoIssuesNewRoute
  '/_protected/$owner/$repo/pull/$pullId': typeof ProtectedOwnerRepoPullPullIdRoute
  '/_protected/$owner/$repo/review/$pullId': typeof ProtectedOwnerRepoReviewPullIdRoute
  '/_protected/$owner/$repo/tree/$': typeof ProtectedOwnerRepoTreeSplatRoute
  '/_protected/$owner/$repo/issues/': typeof ProtectedOwnerRepoIssuesIndexRoute
  '/_protected/$owner/$repo/actions/runs/$runId': typeof ProtectedOwnerRepoActionsRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/inbox'
    | '/issues'
    | '/pulls'
    | '/repos'
    | '/reviews'
    | '/settings'
    | '/settings/shortcuts'
    | '/api/auth/$'
    | '/api/webhooks/github'
    | '/$owner/'
    | '/settings/'
    | '/$owner/$repo/pulls'
    | '/api/github/app/authorize'
    | '/api/github/app/callback'
    | '/$owner/$repo/'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/issues/$issueId'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pull/$pullId'
    | '/$owner/$repo/review/$pullId'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/issues/'
    | '/$owner/$repo/actions/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/inbox'
    | '/issues'
    | '/pulls'
    | '/repos'
    | '/reviews'
    | '/'
    | '/settings/shortcuts'
    | '/api/auth/$'
    | '/api/webhooks/github'
    | '/$owner'
    | '/settings'
    | '/$owner/$repo/pulls'
    | '/api/github/app/authorize'
    | '/api/github/app/callback'
    | '/$owner/$repo'
    | '/$owner/$repo/blob/$'
    | '/$owner/$repo/commit/$sha'
    | '/$owner/$repo/compare/$'
    | '/$owner/$repo/issues/$issueId'
    | '/$owner/$repo/issues/new'
    | '/$owner/$repo/pull/$pullId'
    | '/$owner/$repo/review/$pullId'
    | '/$owner/$repo/tree/$'
    | '/$owner/$repo/issues'
    | '/$owner/$repo/actions/runs/$runId'
  id:
    | '__root__'
    | '/$'
    | '/_protected'
    | '/login'
    | '/privacy'
    | '/setup'
    | '/terms'
    | '/_protected/inbox'
    | '/_protected/issues'
    | '/_protected/pulls'
    | '/_protected/repos'
    | '/_protected/reviews'
    | '/_protected/settings'
    | '/_protected/'
    | '/_protected/settings/shortcuts'
    | '/api/auth/$'
    | '/api/webhooks/github'
    | '/_protected/$owner/'
    | '/_protected/settings/'
    | '/_protected/$owner/$repo/pulls'
    | '/api/github/app/authorize'
    | '/api/github/app/callback'
    | '/_protected/$owner/$repo/'
    | '/_protected/$owner/$repo/blob/$'
    | '/_protected/$owner/$repo/commit/$sha'
    | '/_protected/$owner/$repo/compare/$'
    | '/_protected/$owner/$repo/issues/$issueId'
    | '/_protected/$owner/$repo/issues/new'
    | '/_protected/$owner/$repo/pull/$pullId'
    | '/_protected/$owner/$repo/review/$pullId'
    | '/_protected/$owner/$repo/tree/$'
    | '/_protected/$owner/$repo/issues/'
    | '/_protected/$owner/$repo/actions/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SetupRoute: typeof SetupRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhooksGithubRoute: typeof ApiWebhooksGithubRoute
  ApiGithubAppAuthorizeRoute: typeof ApiGithubAppAuthorizeRoute
  ApiGithubAppCallbackRoute: typeof ApiGithubAppCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reviews': {
      id: '/_protected/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ProtectedReviewsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/repos': {
      id: '/_protected/repos'
      path: '/repos'
      fullPath: '/repos'
      preLoaderRoute: typeof ProtectedReposRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pulls': {
      id: '/_protected/pulls'
      path: '/pulls'
      fullPath: '/pulls'
      preLoaderRoute: typeof ProtectedPullsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/issues': {
      id: '/_protected/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof ProtectedIssuesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/inbox': {
      id: '/_protected/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof ProtectedInboxRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/$owner/': {
      id: '/_protected/$owner/'
      path: '/$owner'
      fullPath: '/$owner/'
      preLoaderRoute: typeof ProtectedOwnerIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/webhooks/github': {
      id: '/api/webhooks/github'
      path: '/api/webhooks/github'
      fullPath: '/api/webhooks/github'
      preLoaderRoute: typeof ApiWebhooksGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/settings/shortcuts': {
      id: '/_protected/settings/shortcuts'
      path: '/shortcuts'
      fullPath: '/settings/shortcuts'
      preLoaderRoute: typeof ProtectedSettingsShortcutsRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/$owner/$repo/': {
      id: '/_protected/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof ProtectedOwnerRepoIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/github/app/callback': {
      id: '/api/github/app/callback'
      path: '/api/github/app/callback'
      fullPath: '/api/github/app/callback'
      preLoaderRoute: typeof ApiGithubAppCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/app/authorize': {
      id: '/api/github/app/authorize'
      path: '/api/github/app/authorize'
      fullPath: '/api/github/app/authorize'
      preLoaderRoute: typeof ApiGithubAppAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/$owner/$repo/pulls': {
      id: '/_protected/$owner/$repo/pulls'
      path: '/$owner/$repo/pulls'
      fullPath: '/$owner/$repo/pulls'
      preLoaderRoute: typeof ProtectedOwnerRepoPullsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/issues/': {
      id: '/_protected/$owner/$repo/issues/'
      path: '/$owner/$repo/issues'
      fullPath: '/$owner/$repo/issues/'
      preLoaderRoute: typeof ProtectedOwnerRepoIssuesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/tree/$': {
      id: '/_protected/$owner/$repo/tree/$'
      path: '/$owner/$repo/tree/$'
      fullPath: '/$owner/$repo/tree/$'
      preLoaderRoute: typeof ProtectedOwnerRepoTreeSplatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/review/$pullId': {
      id: '/_protected/$owner/$repo/review/$pullId'
      path: '/$owner/$repo/review/$pullId'
      fullPath: '/$owner/$repo/review/$pullId'
      preLoaderRoute: typeof ProtectedOwnerRepoReviewPullIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/pull/$pullId': {
      id: '/_protected/$owner/$repo/pull/$pullId'
      path: '/$owner/$repo/pull/$pullId'
      fullPath: '/$owner/$repo/pull/$pullId'
      preLoaderRoute: typeof ProtectedOwnerRepoPullPullIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/issues/new': {
      id: '/_protected/$owner/$repo/issues/new'
      path: '/$owner/$repo/issues/new'
      fullPath: '/$owner/$repo/issues/new'
      preLoaderRoute: typeof ProtectedOwnerRepoIssuesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/issues/$issueId': {
      id: '/_protected/$owner/$repo/issues/$issueId'
      path: '/$owner/$repo/issues/$issueId'
      fullPath: '/$owner/$repo/issues/$issueId'
      preLoaderRoute: typeof ProtectedOwnerRepoIssuesIssueIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/compare/$': {
      id: '/_protected/$owner/$repo/compare/$'
      path: '/$owner/$repo/compare/$'
      fullPath: '/$owner/$repo/compare/$'
      preLoaderRoute: typeof ProtectedOwnerRepoCompareSplatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/commit/$sha': {
      id: '/_protected/$owner/$repo/commit/$sha'
      path: '/$owner/$repo/commit/$sha'
      fullPath: '/$owner/$repo/commit/$sha'
      preLoaderRoute: typeof ProtectedOwnerRepoCommitShaRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/blob/$': {
      id: '/_protected/$owner/$repo/blob/$'
      path: '/$owner/$repo/blob/$'
      fullPath: '/$owner/$repo/blob/$'
      preLoaderRoute: typeof ProtectedOwnerRepoBlobSplatRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/$owner/$repo/actions/runs/$runId': {
      id: '/_protected/$owner/$repo/actions/runs/$runId'
      path: '/$owner/$repo/actions/runs/$runId'
      fullPath: '/$owner/$repo/actions/runs/$runId'
      preLoaderRoute: typeof ProtectedOwnerRepoActionsRunsRunIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsShortcutsRoute: typeof ProtectedSettingsShortcutsRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsShortcutsRoute: ProtectedSettingsShortcutsRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedRouteChildren {
  ProtectedInboxRoute: typeof ProtectedInboxRoute
  ProtectedIssuesRoute: typeof ProtectedIssuesRoute
  ProtectedPullsRoute: typeof ProtectedPullsRoute
  ProtectedReposRoute: typeof ProtectedReposRoute
  ProtectedReviewsRoute: typeof ProtectedReviewsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedOwnerIndexRoute: typeof ProtectedOwnerIndexRoute
  ProtectedOwnerRepoPullsRoute: typeof ProtectedOwnerRepoPullsRoute
  ProtectedOwnerRepoIndexRoute: typeof ProtectedOwnerRepoIndexRoute
  ProtectedOwnerRepoBlobSplatRoute: typeof ProtectedOwnerRepoBlobSplatRoute
  ProtectedOwnerRepoCommitShaRoute: typeof ProtectedOwnerRepoCommitShaRoute
  ProtectedOwnerRepoCompareSplatRoute: typeof ProtectedOwnerRepoCompareSplatRoute
  ProtectedOwnerRepoIssuesIssueIdRoute: typeof ProtectedOwnerRepoIssuesIssueIdRoute
  ProtectedOwnerRepoIssuesNewRoute: typeof ProtectedOwnerRepoIssuesNewRoute
  ProtectedOwnerRepoPullPullIdRoute: typeof ProtectedOwnerRepoPullPullIdRoute
  ProtectedOwnerRepoReviewPullIdRoute: typeof ProtectedOwnerRepoReviewPullIdRoute
  ProtectedOwnerRepoTreeSplatRoute: typeof ProtectedOwnerRepoTreeSplatRoute
  ProtectedOwnerRepoIssuesIndexRoute: typeof ProtectedOwnerRepoIssuesIndexRoute
  ProtectedOwnerRepoActionsRunsRunIdRoute: typeof ProtectedOwnerRepoActionsRunsRunIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedInboxRoute: ProtectedInboxRoute,
  ProtectedIssuesRoute: ProtectedIssuesRoute,
  ProtectedPullsRoute: ProtectedPullsRoute,
  ProtectedReposRoute: ProtectedReposRoute,
  ProtectedReviewsRoute: ProtectedReviewsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedOwnerIndexRoute: ProtectedOwnerIndexRoute,
  ProtectedOwnerRepoPullsRoute: ProtectedOwnerRepoPullsRoute,
  ProtectedOwnerRepoIndexRoute: ProtectedOwnerRepoIndexRoute,
  ProtectedOwnerRepoBlobSplatRoute: ProtectedOwnerRepoBlobSplatRoute,
  ProtectedOwnerRepoCommitShaRoute: ProtectedOwnerRepoCommitShaRoute,
  ProtectedOwnerRepoCompareSplatRoute: ProtectedOwnerRepoCompareSplatRoute,
  ProtectedOwnerRepoIssuesIssueIdRoute: ProtectedOwnerRepoIssuesIssueIdRoute,
  ProtectedOwnerRepoIssuesNewRoute: ProtectedOwnerRepoIssuesNewRoute,
  ProtectedOwnerRepoPullPullIdRoute: ProtectedOwnerRepoPullPullIdRoute,
  ProtectedOwnerRepoReviewPullIdRoute: ProtectedOwnerRepoReviewPullIdRoute,
  ProtectedOwnerRepoTreeSplatRoute: ProtectedOwnerRepoTreeSplatRoute,
  ProtectedOwnerRepoIssuesIndexRoute: ProtectedOwnerRepoIssuesIndexRoute,
  ProtectedOwnerRepoActionsRunsRunIdRoute:
    ProtectedOwnerRepoActionsRunsRunIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SetupRoute: SetupRoute,
  TermsRoute: TermsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhooksGithubRoute: ApiWebhooksGithubRoute,
  ApiGithubAppAuthorizeRoute: ApiGithubAppAuthorizeRoute,
  ApiGithubAppCallbackRoute: ApiGithubAppCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
