/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedReviewsRouteImport } from './routes/_protected/reviews'
import { Route as ProtectedPullRequestsRouteImport } from './routes/_protected/pull-requests'
import { Route as ProtectedIssuesRouteImport } from './routes/_protected/issues'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReviewsRoute = ProtectedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPullRequestsRoute = ProtectedPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedIssuesRoute = ProtectedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/issues': typeof ProtectedIssuesRoute
  '/pull-requests': typeof ProtectedPullRequestsRoute
  '/reviews': typeof ProtectedReviewsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/issues': typeof ProtectedIssuesRoute
  '/pull-requests': typeof ProtectedPullRequestsRoute
  '/reviews': typeof ProtectedReviewsRoute
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/issues': typeof ProtectedIssuesRoute
  '/_protected/pull-requests': typeof ProtectedPullRequestsRoute
  '/_protected/reviews': typeof ProtectedReviewsRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/issues'
    | '/pull-requests'
    | '/reviews'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/issues' | '/pull-requests' | '/reviews' | '/' | '/api/auth/$'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/issues'
    | '/_protected/pull-requests'
    | '/_protected/reviews'
    | '/_protected/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reviews': {
      id: '/_protected/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ProtectedReviewsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pull-requests': {
      id: '/_protected/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ProtectedPullRequestsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/issues': {
      id: '/_protected/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof ProtectedIssuesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedIssuesRoute: typeof ProtectedIssuesRoute
  ProtectedPullRequestsRoute: typeof ProtectedPullRequestsRoute
  ProtectedReviewsRoute: typeof ProtectedReviewsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIssuesRoute: ProtectedIssuesRoute,
  ProtectedPullRequestsRoute: ProtectedPullRequestsRoute,
  ProtectedReviewsRoute: ProtectedReviewsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
